### ISSUE TITLE
Improved version 

### ISSUE THREAD

**Issue by Y0Sam** [Finomnis/ResistorLabels#6]
Hello Finomnis,
I have extended you original python script such that it will work with other labels and that you can enter on long list of resistor values.
The script will automatically generate the number of pages needed.
I am not familiar with github to make it available.
Please let me know if you want to get it in github.

**Comment by Finomnis** [comment]
Hey Y0Sam!

Of course I'm interested in improvements.
If you don't know how to make a pull request on github, please post the changed script on https://pastebin.com/ and send me the link here. I will then create a pull request for you where we can discuss your changes.

Greetings,
Martin

**Comment by Y0Sam** [comment]
Hi Martin,

I will have a look tonight.

Groeten Joost

**Comment by Finomnis** [comment]
Closed due to inactivity.
