### ISSUE TITLE
Multiple Pages Feature

### ISSUE THREAD

**Issue by azrieltomas** [Finomnis/ResistorLabels#7]
Hello,
I've done a modification that uses a single long list of resistor values (rather than the original 2D array) and outputs to multiple pages where required. If you're interested I can fork & make a pull request.

My update still uses the same three label layouts, but adds a column & row to the layout type. Then uses numpy to pad & rearrange the list into a 2D array, which are rendered and exported as before. I'm not a big python programmer so it may not be the most elegant but it seems to work well.

**Comment by Finomnis** [comment]
In general I like the idea. There is one usecase, though, which requires a 2D layout: if you want to print on sticker pages that have stickers removed already. For example, you printed all your stickers and need another new value. You have a half used sticker page, so you want to position the new value on the next unused sticker.
I specifically did the 2d layout for this usecase, because I didn't know from the beginning which resistor types I will have in the bags and printed new ones as I bought them.

**Comment by azrieltomas** [comment]
Of course! I definitely did it more for my specific use case which was just "making a new set, no regard for previous prints," but that's something I'll expand upon a little more to see if there's a user friendly (esp wrt non-programmers) for it to work. Either way I'm happy to leave it just as a personal fork if you don't think it's necessary. 
And yeah numpy was not my ideal - it's a lot for some simple array maths, it was more chosen for simplicity of programming. But also something I will investigate replacing with a couple loops instead.
Here's the pastebin if you'd like to take a look though: https://pastebin.com/LafCNFM8

**Comment by Finomnis** [comment]
In general, I think this is not a bad idea, but it would need wie some cleanup. I don't want to add any extra complexity in `main()`. That includes the comments inside of it, and the `README.md` file. I spent a lot of time to structure the project in a way that the readme file and in general the entire usage of the script is as simple as possible. Don't underestimate the effect such a change would have on those.

**Comment by azrieltomas** [comment]
All good points. I'll have a think and see what I can come up with that work with the existing methods. And even then, no dramas if you prefer not to incorporate any changes, as I said I'm happy to leave it as a fork. Thanks!

**Comment by Finomnis** [comment]
After merging #18  and #16, it is now supported that either a 1D or 2D array can get specified, and it will get automatically broken down into rows, columns and pages.

Does this satisfy your usecase?

Greetz

**Comment by Finomnis** [comment]
@azrieltomas Without further activity, I will close this issue in a couple of days because I assume that the recent changes solved your problem.

**Comment by azrieltomas** [comment]
Sorry for the delay - yeah that's fantastic. Thanks

**Comment by Finomnis** [comment]
> Sorry for the delay - yeah that's fantastic. Thanks

No problem, glad to hear :)

Didn't mean to pressure you, just weren't sure if you are still active on github and see my message :)
